(cl:defpackage rubbing_hand-srv
  (:use )
  (:export
   "SETFLOAT64"
   "<SETFLOAT64-REQUEST>"
   "SETFLOAT64-REQUEST"
   "<SETFLOAT64-RESPONSE>"
   "SETFLOAT64-RESPONSE"
   "SET2FLOAT64"
   "<SET2FLOAT64-REQUEST>"
   "SET2FLOAT64-REQUEST"
   "<SET2FLOAT64-RESPONSE>"
   "SET2FLOAT64-RESPONSE"
  ))

