(cl:in-package rubbing_hand-msg)
(cl:export '(HEADER-VAL
          HEADER
          INTERVAL-VAL
          INTERVAL
          MV-VAL
          MV
          DEGREE_OF_FINGER-VAL
          DEGREE_OF_FINGER
          OFFSET_DEGREE_OF_FINGER-VAL
          OFFSET_DEGREE_OF_FINGER
          MV_DEGREE_OF_FINGER-VAL
          MV_DEGREE_OF_FINGER
          DEGREE_OF_SURFACE-VAL
          DEGREE_OF_SURFACE
          POS_OF_SURFACE-VAL
          POS_OF_SURFACE
          MV_S-VAL
          MV_S
          OBJ_ORIENTATION-VAL
          OBJ_ORIENTATION
          OBJ_ORIENTATION_FILTERED-VAL
          OBJ_ORIENTATION_FILTERED
          D_OBJ_ORIENTATION_FILTERED-VAL
          D_OBJ_ORIENTATION_FILTERED
          TARGET_OBJ_ORIENTATION-VAL
          TARGET_OBJ_ORIENTATION
          TARGET_D_OBJ_ORIENTATION-VAL
          TARGET_D_OBJ_ORIENTATION
          OMEGA_D-VAL
          OMEGA_D
          MV_I-VAL
          MV_I
          MV_O-VAL
          MV_O
          PROCESS_F-VAL
          PROCESS_F
          DEBAG-VAL
          DEBAG
))